baseurl = "https://scottcwilson.github.io/"
languageCode = "en-us"
title = "Scott C Wilson"
theme = "aglaus2"
copyright = "Scott C Wilson"

[author]
	name = "Scott C Wilson"
	linkedin = "scottcwilson"
	twitter = "scottcwilson"
	twitter2 = "thatsoftwareguy"
	github = "scottcwilson"
	facebook = "scottcwilson"

[params]
	description = "My Sites"
        dateform = "Mon, Jan 2, 2006"
	linkedin = "https://www.linkedin.com/in/scottcwilson"
	twitter = "https://twitter.com/scottcwilson"
	github = "https://github.com/scottcwilson"
        GravatarHash = "750b75109b76470b82336ae826483eb1"
